name: assk_connect
description: Next-generation local gigs & bounties platform with enterprise-grade architecture

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management & Architecture
  flutter_bloc: ^8.1.3
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  equatable: ^2.0.5
  
  # Navigation
  go_router: ^12.1.3
  
  # HTTP & API
  dio: ^5.3.2
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Real-time Communication
  signalr_netcore: ^1.3.8
  
  # Local Storage & Caching
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # UI Components
  cupertino_icons: ^1.0.6
  material_design_icons_flutter: ^7.0.7296
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # Maps & Location
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Animations
  lottie: ^2.7.0
  rive: ^0.12.4
  flutter_animate: ^4.2.0
  
  # Authentication & Security
  local_auth: ^2.1.7
  crypto: ^3.0.3
  
  # Notifications
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.0
  
  # Payments
  stripe_platform_interface: ^8.0.0
  
  # Utilities
  freezed_annotation: ^2.4.1
  intl: ^0.18.1
  url_launcher: ^6.2.1
  permission_handler: ^11.1.0
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  
  # Development & Debugging
  logger: ^2.0.2+1
  flutter_stetho: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  retrofit_generator: ^7.0.8
  hive_generator: ^2.0.1
  
  # Linting & Analysis
  flutter_lints: ^3.0.1
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.9

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
